### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by Ha0-W** [xyutao/fscil#13]
I wonder how to get the result of session > 2. We will train on the 25 images for some epochs. We evaluate the model after each epoch and choose the best result or just after the last epoch?

**Comment by xyutao** [comment]
Choose an intermediate model with a better performance trade-off between the old and new classes. 

We've developed the acquisition-memory curves (in Fig.7 of supplementary material) to justify the selection of models, where a F score is computed to balance the accuracies of old and new classes. In this way, we can get a better recognition performance for longer sequence of learning. 

You can access the CVPR website http://conferences.computer.org/cvpr, and download the supplementary material.
username: cvpr20
passwd: conf20//

**Comment by Ha0-W** [comment]
Thanks!
