### ISSUE TITLE
Figure 4 Results

### ISSUE THREAD

**Issue by akashgokul** [xyutao/fscil#15]
Hi, thanks for all of your help.

Do you have the exact numbers for the accuracies in Fig 4 of the paper?

**Comment by xyutao** [comment]
Hi, the exact numbers of Fig.4's accuracies had been reported in README.md of this repository. For more results, you may access the CVPR website http://conferences.computer.org/cvpr, and download the supplementary material.

username: cvpr20
passwd: conf20//
