### ISSUE TITLE
Node & Exemplar Saving

### ISSUE THREAD

**Issue by akashgokul** [xyutao/fscil#16]
Hi, 
  For your experiments, e.g. Figure 4 and Table 2, how many nodes did you save? What is the memory overhead for saving such amount of nodes? Also for iCarl and EEIL how many exemplars did you save?

**Comment by xyutao** [comment]
400 nodes for the base classes and 1 for each new class. We use the same number of exemplars for other methods for a fair comparison under the same memory overhead.

**Comment by xialeiliu** [comment]
Do you mean that 400 exemplars in total are kept for base classes and 1 exemplar is kept for each new class? (For all exemplar-based methods)

**Comment by prachigarg23** [comment]
Hi @xyutao, can you please confirm if only 1 exemplar was stored for every new class? I am unable to find this detail in the paper. @xialeiliu, any idea if the results are reproduce-able with this setting of 400 base class exemplars and 1 exemplar per new class.
