### ISSUE TITLE
ResNet18 for cifar100

### ISSUE THREAD

**Issue by solucky-95** [xyutao/fscil#18]
https://github.com/xyutao/fscil/blob/e76d37c9bdb64474b323ee97c312148fb704e91f/model/cifar_resnet_v1.py#L217

Hi,
It seems that you are using ResNet-20 for cifar100 (1 + 3x2 + 3x2 +3x2 +1 =20). Have I misunderstood it?

**Comment by xyutao** [comment]
That's right. The so called ResNet18-thumbnail version for CIFAR100 accurately has 20 layers.
