### ISSUE TITLE
The split of validation dataset

### ISSUE THREAD

**Issue by MoonJian** [xyutao/fscil#2]
Thanks for your fantastic work, but I have a question about the validation dataset: whether you split the training set into two parts: train and val, when train the base model, and the number of val samples per class in base and new sessions?

**Comment by xyutao** [comment]
The  new class training sets are constructed by picking N samples for each class from the original dataset. So just pick another N samples for validation purpose.

**Comment by MoonJian** [comment]
Thanks for your reply~
