### ISSUE TITLE
Question about full-shot setting

### ISSUE THREAD

**Issue by EdenBelouadah** [xyutao/fscil#20]
Hello,
Thank you for your interesting work. 
I have a question concerning the full-shot setting. When you compared TOPIC with other state-of-the-art approaches, how many exemplars did you use for these approaches? and did you choose the exemplars randomly or by herding? 

Thank you.

**Comment by xyutao** [comment]
Hi @EdenBelouadah, the number of the exemplars for other approaches is the same as that of the neural gas nodes, which is (400 + k * C), i.e., 400 exemplars in total for all the base classes and k=1 exemplar for each few-shot new class. The exemplars are selected randomly.

**Comment by EdenBelouadah** [comment]
Hello, 
Thank you for your quick reply. 
In the paragraphe (The effect of the number of training samples). You say "We grow NG by adding 20 nodes for each new session, which we have 400 + 20(t-1) NG Nodes at session (t-1).  I understand that for mini-imagenet (where we have 60 base classes and 40 incremental), you use 400 exemplars shared by all the 60 base classes, while for each new session, the 5 new classes will share 20 exemplars, it means each incremetal class will have 4 exemplars, is this right? 

Also, can you provide the numerical values used to plot the figure 5(b), please ?

**Comment by xyutao** [comment]
@EdenBelouadah, yes, for full-shot setting, its (400 + 20 * (t-1)) = (400 + 4 * C). Each incremental class will have 4 exemplars. The results of Fig.5 have been provided in Table 12 in supplementary materials, as well as more details on model selection and evaluation. You may download it by accessing http://conferences.computer.org/cvpr

username: cvpr20
passwd: conf20//

**Comment by EdenBelouadah** [comment]
Thank you, it is much clearer now.  One last question, are you reporting the top5 or the top1 accuracy in the paper?

**Comment by xyutao** [comment]
Top-1 accuracy for all datasets.

**Comment by EdenBelouadah** [comment]
Thank you very much for all the answers.
