### ISSUE TITLE
About neural gas mechanism

### ISSUE THREAD

**Issue by petercheng85** [xyutao/fscil#3]
I have the honor to read your work! And I have a simple but maybe stupid question about the mechanism of neural gas. In most CIL works, they set a parameter for the size of memory with fixed capacity. I wonder how to control the the memory size for old data in neural gas (e.g. node deletion)?

Thank you for taking the time to read this!

**Comment by xyutao** [comment]
For memory efficiency, the adjacent nodes with the same label can be merged to a single node by weighted aggregating, but it is not necessary for the few-shot setting. You just need to guarantee each new class has at least one corresponding NG node. 

For the experimental comparison under a fixed capacity, we simply fix the memory size M = (400 + C) for all methods, where 400 is the number of base NG nodes and C is the number of all encountered new classes.

**Comment by petercheng85** [comment]
Thanks for your reply!
