### ISSUE TITLE
Question about dataloader

### ISSUE THREAD

**Issue by Nan-S** [xyutao/fscil#6]
Hi I am interested in this few shot class incremental learning setting, I have following questions regarding to the dataloader.py:
1. What's the meaning of fix_class in following code? how to use it? 
 def __init__(self, logger, root=os.path.join(base.data_dir(), 'datasets', 'cifar100'),
                 fine_label=False, train=True, transform=None, c_way=5, k_shot=5, fix_class=None, base_class=0)
https://github.com/xyutao/fscil/blob/6dd827fb780bb474cdd34d5f0c3c8a624b9d7c85/dataloader/dataloader.py#L31
2. When want to setup base class training dataset, how to call this function to form the dataset? set base_class=60?

**Comment by xyutao** [comment]
1. fix_class is a list of the class indices to be selected as new classes and then fixed for the experiments. If you intend to randomly select new classes for the next session (not use a fixed set), just leave it as the default 'None' value.
2. For training the base session, set fix_class to be the list of the base class indices (e.g. fix_class=np.arange(60)) and set base_class=len(fix_class) (e.g. base_class=60)

**Comment by Nan-S** [comment]
Thanks for explanation, I will proceed to close this issue.
